<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Concour;

/**
 * ConcourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcourRepository extends \Doctrine\ORM\EntityRepository
{
    public  function Rechercher(Concour $concour){
       $query =  $this->createQueryBuilder('c');
       if($concour->getReference())
           $query->andWhere('c.reference LIKE :ref')->setParameter('ref','%'.$concour->getReference().'%');
       if($concour->getAnnee())
           $query->andWhere('c.annee LIKE :an')->setParameter('an','%'.$concour->getAnnee().'%');
       if($concour->getLieu())
           $query->andWhere('c.lieu LIKE :lieu')->setParameter('lieu','%'.$concour->getAnnee().'%');
       if($concour->getMotsCle())
           $query->andWhere('c.mots_cle LIKE :mots_cle')->setParameter('mots_cle','%'.$concour->getMotsCle().'%');

       if($concour->getDateDebut())
           $query->andWhere('c.dateDebut = :datedebut')->setParameter('datedebut',$concour->getDateDebut());

       if($concour->getDateFin())
           $query->andWhere('c.dateFin = :DateFin')->setParameter('getDateFin',$concour->getDateFin());

    return $query->getQuery()->getResult();
    }
}
