<?php

namespace AppBundle\Repository;
use AuthentificationBundle\Entity\Candidat;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function formationsPourCandidat(Candidat $candidat){
        $formations= [];
        $SQL = $this->getEntityManager()->getConnection();
        $query = $SQL->prepare('
        SELECT f.id 
        FROM formation f , post_format fs , inscription i  , concour_poste cp, concour c
        WHERE f.id = fs.formation_id AND fs.poste_id = cp.id_poste AND c.reference = cp.id_concour AND i.id_concour = c.reference
        AND i.id_candidat = :id 
        GROUP BY f.id ;
        ');
        $query->bindValue('id',$candidat->getId(),\PDO::PARAM_INT);
        $query->execute();
        $results = $query->fetchAll();
        foreach ($results as $result){
            array_push($formations,$this->find($result['id']));
        }
        return $formations;
    }
}
